// Generated by ever-better. This file is yours — edit it.
//
// Every rule below is an ERROR, and every violation that existed when you ran
// `ever-better freeze` is recorded in eslint-suppressions.json. Old code is grandfathered;
// new code is held to the whole standard from the first commit. Do not soften a rule to make
// a red build green — the suppressions file already did that, once, on purpose.
//
// Type assertions are banned outright: `as`, `<T>x`, `!`, `@ts-ignore`, `@ts-nocheck`. Each is a
// claim the compiler could not check and that no reviewer can see. Write a type guard instead —
// `const isThing = (v: unknown): v is Thing => ...` — which is testable, narrows for every
// caller, and fails at the boundary where the data was actually wrong.

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import sonarjs from "eslint-plugin-sonarjs";
import prettierRecommended from "eslint-plugin-prettier/recommended";
import security from "eslint-plugin-security";

export default tseslint.config(
  { ignores: ["dist/**", "build/**", "coverage/**", "node_modules/**", ".vercel/**"] },
  {
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
  },

  js.configs.recommended,
  // strictTypeChecked, not recommended: the type-aware rules that find real bugs are only in
  // the TypeChecked presets, and the strict variant is where the `any` family lives.
  tseslint.configs.strictTypeChecked,
  // The two are disjoint; typescript-eslint's own advice is to use both.
  tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
  },
  sonarjs.configs.recommended,
  security.configs.recommended,
  prettierRecommended,

  { languageOptions: { globals: globals.node } },

  {
    // Types as a second rule set. `any` and `!` are how a type system gets talked out of
    // doing its job, and both are invisible in review.
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^__" }],
      // A private field nothing reassigns is a constant, and saying so stops the next reader
      // looking for the write that never happens.
      "@typescript-eslint/prefer-readonly": "error",
      // `as` asserts what the compiler could not check, and it is invisible in review. Write a
      // type guard instead — the guard is testable and the assertion is a promise.
      "@typescript-eslint/consistent-type-assertions": ["error", { assertionStyle: "never" }],
      // The other doors out of the type system. `@ts-expect-error` survives only with a
      // written reason, because it is the one that fails loudly when it stops being needed.
      "@typescript-eslint/ban-ts-comment": [
        "error",
        {
          "ts-ignore": true,
          "ts-nocheck": true,
          "ts-check": false,
          "ts-expect-error": "allow-with-description",
          minimumDescriptionLength: 10,
        },
      ],
    },
  },
  {
    rules: {
      // typescript-eslint enables both of these for `.ts` files only, so the JavaScript repo
      // that actually contains `var` is the one nothing checks — and `.jsx`, `.vue` and `.mjs`
      // stay uncovered after a migration. `eslint --fix` converts the lot: var -> let, then
      // let -> const everywhere nothing reassigns.
      "no-var": "error",
      "prefer-const": "error",
      // A reassigned parameter makes the argument name lie for the rest of the function, and
      // the caller cannot see it happen.
      "no-param-reassign": "error",
    },
  },
  {
    // Size and complexity guards. These are the ones that turn into refactoring work rather
    // than one-line fixes, which is exactly why they are recorded rather than negotiated.
    rules: {
      "max-lines": ["error", { max: 600, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["error", { max: 50, skipBlankLines: true, skipComments: true }],
      complexity: ["error", 15],
      "max-depth": ["error", 4],
      "max-nested-callbacks": ["error", 4],
      "max-params": ["error", 6],
      "sonarjs/cognitive-complexity": ["error", 15],
    },
  },
  {
    rules: {
      // A `return` inside the `if` makes the `else` a level of indentation nobody needs.
      "no-else-return": ["error", { allowElseIf: false }],
      // Two `if`s that are one `&&`: a level of nesting for no extra branch.
      "sonarjs/no-collapsible-if": "error",
    },
  },
  {
    rules: {
      // A loop counter and a discarded binding are not what this is aimed at; a variable called
      // `d` holding a customer record is. `js`, `fs`, `os` are the conventional module aliases.
      "id-length": ["error", { min: 3, exceptions: ["_", "i", "j", "k", "id", "ok", "to", "up", "js", "fs", "os"] }],
    },
  },
  {
    // A spec repeats itself by nature and its length is not a comprehension problem.
    // This repo's specs live under tests/, not test/.
    files: ["tests/**"],
    rules: {
      "max-lines": "off",
      "max-lines-per-function": "off",
      "sonarjs/no-duplicate-string": "off",
    },
  },
  {
    files: ["**/*.config.js", "**/*.config.mjs", "**/*.config.cjs"],
    languageOptions: { parserOptions: { projectService: false } },
    ...tseslint.configs.disableTypeChecked,
  },
  {
    // The file-storage layer takes its path as a parameter so tests can point it at a temp
    // directory. That path only ever comes from our own default constant or a caller in this
    // codebase — never from a request, the RSS feed, or an LLM response — so this rule has no
    // untrusted input to catch here and only flags the dependency-injection pattern itself.
    files: ["src/infrastructure/store/**", "tests/infrastructure/processedStore.test.ts"],
    rules: {
      "security/detect-non-literal-fs-filename": "off",
    },
  },
);
